Phg 116
tair/phylogenes-ui pull request #28
Opened 2019-03-07 00:39 UTC by richardli515

2019-03-07 00:44 UTC, richardli515 commented on src/components/search/SearchResult.vue
> +            // newSearch() {
delete the funciton

2019-03-07 00:46 UTC, richardli515 commented on src/views/TreeBrowse.vue
> +                // if(this.$refs.sr) {
check if we can remove $refs.sr and $ refs.sf

2019-03-07 20:46 UTC, trilok2000 commented on src/views/TreeBrowse.vue
> +        // beforeRouteEnter (to, from, next) {
can we remove this commented code?

2019-03-07 20:46 UTC, trilok2000 commented on src/views/TreeBrowse.vue
> +        // },
can we remove this commented code?

2019-03-07 20:46 UTC, trilok2000 commented on src/views/TreeBrowse.vue
> +            // },
can we remove this commented code?

2019-03-07 20:47 UTC, trilok2000 commented on src/components/search/SearchResult.vue
> +            // },
can we remove this commented code?

2019-03-07 20:47 UTC, trilok2000 commented on src/components/search/SearchResult.vue
> +            //         return;
can we remove this commented code?

2019-03-07 20:47 UTC, trilok2000 commented on src/components/search/SearchResult.vue
> +            // gotoPage(page) {
can we remove this commented code?

2019-03-07 20:48 UTC, trilok2000 requested changes
pls remove the commented code. and i think we are good to go with merge. thanks!

2019-03-08 00:40 UTC, richardli515 commented on src/views/TreeBrowse.vue
> +        // beforeRouteEnter (to, from, next) {
yes. removed

2019-03-08 00:41 UTC, richardli515 commented on src/views/TreeBrowse.vue
> +        // },
yes. removed.

2019-03-08 00:41 UTC, richardli515 commented on src/views/TreeBrowse.vue
> +            // },
yes. removed.

2019-03-08 00:42 UTC, richardli515 commented on src/components/search/SearchResult.vue
> +            // gotoPage(page) {
yes. removed.

2019-03-08 00:43 UTC, richardli515 commented on src/components/search/SearchResult.vue
> +            //         return;
removed

2019-03-08 00:43 UTC, richardli515 commented on src/components/search/SearchResult.vue
> +            // },
removed

2019-03-08 00:44 UTC, richardli515 commented on src/components/search/SearchResult.vue
> +            // gotoPage(page) {
removed

2019-03-08 01:01 UTC, merged